
import { supabase, isSupabaseEnabled } from './supabaseClient';
import { authenticatedApiFetch } from './authenticatedApi';
import { Routine, DietPlan, Client } from "../types";

let lastGeminiErrorMessage = "";
const GEMINI_CLIENT_TIMEOUT_MS = Number((import.meta as any).env?.VITE_GEMINI_CLIENT_TIMEOUT_MS || 60000);
const GEMINI_DEBUG = Boolean((import.meta as any).env?.DEV);
const geminiLog = (...args: unknown[]) => {
  if (GEMINI_DEBUG) console.log(...args);
};
const geminiError = (...args: unknown[]) => {
  if (GEMINI_DEBUG) console.error(...args);
};
export type GeminiOutputLanguage = "es" | "en";

const fallbackCopy = {
  es: {
    generalTraining: "Entrenamiento General",
    routineTitle: (goal: string) => `Plan Base: ${goal}`,
    routineDescription: "Generado con parámetros estándar. Por favor verifica tu conexión para obtener una versión optimizada por IA PRO.",
    dietTitle: "Plan Nutricional Base",
    dietNotes: "Generado con parámetros nutricionales estándar. Verifica tu conexión para obtener optimización por IA PRO.",
    aiRoutineTitle: "Nueva Rutina AI",
    aiRoutineSummary: "Generada por IA",
    aiDietTitle: "Plan Nutricional AI",
    aiDietSummary: "Generado por IA",
    mealName: "Comida Saludable",
    mealDescription: "Porción balanceada según las recomendaciones del plan.",
    balancedMeal: (meal: string) => `${meal} Balanceado`,
    healthyMeal: "Preparación saludable rica en proteínas limpias y carbohidratos complejos.",
    hydration: "Mantener una hidratación de al menos 2.5 litros de agua al día.",
    adherence: "Asegura la adherencia pesando tus alimentos en crudo si es posible."
  },
  en: {
    generalTraining: "General Training",
    routineTitle: (goal: string) => `Base Plan: ${goal}`,
    routineDescription: "Generated with standard parameters. Please verify your connection to get a PRO AI optimized version.",
    dietTitle: "Base Nutrition Plan",
    dietNotes: "Generated with standard nutrition parameters. Verify your connection to get PRO AI optimization.",
    aiRoutineTitle: "New AI Workout",
    aiRoutineSummary: "Generated by AI",
    aiDietTitle: "AI Nutrition Plan",
    aiDietSummary: "Generated by AI",
    mealName: "Healthy Meal",
    mealDescription: "Balanced portion according to the plan recommendations.",
    balancedMeal: (meal: string) => `Balanced ${meal}`,
    healthyMeal: "Healthy preparation rich in lean proteins and complex carbohydrates.",
    hydration: "Maintain hydration of at least 2.5 liters of water per day.",
    adherence: "Improve adherence by weighing raw ingredients when possible."
  }
};

const DAY_LABELS: Record<GeminiOutputLanguage, string[]> = {
  es: ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo"],
  en: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]
};

const MEAL_LABELS: Record<GeminiOutputLanguage, string[]> = {
  es: ["Desayuno", "Media Mañana", "Almuerzo", "Media Tarde", "Cena"],
  en: ["Breakfast", "Morning Snack", "Lunch", "Afternoon Snack", "Dinner"]
};

const DAY_ALIASES = [
  { es: "Lunes", en: "Monday", keys: ["lunes", "monday", "mon"] },
  { es: "Martes", en: "Tuesday", keys: ["martes", "tuesday", "tue"] },
  { es: "Miércoles", en: "Wednesday", keys: ["miercoles", "miércoles", "wednesday", "wed"] },
  { es: "Jueves", en: "Thursday", keys: ["jueves", "thursday", "thu"] },
  { es: "Viernes", en: "Friday", keys: ["viernes", "friday", "fri"] },
  { es: "Sábado", en: "Saturday", keys: ["sabado", "sábado", "saturday", "sat"] },
  { es: "Domingo", en: "Sunday", keys: ["domingo", "sunday", "sun"] }
] as const;

const normalizeLanguage = (language?: GeminiOutputLanguage): GeminiOutputLanguage => language === "en" ? "en" : "es";

const textKey = (value: any) => String(value || "")
  .normalize("NFD")
  .replace(/[\u0300-\u036f]/g, "")
  .toLowerCase()
  .trim();

const localizeDay = (value: any, language: GeminiOutputLanguage) => {
  const key = textKey(value);
  const match = DAY_ALIASES.find(day => day.keys.some(alias => key.includes(textKey(alias))));
  return match ? match[language] : String(value || "");
};

const getDayLabels = (language: GeminiOutputLanguage) => DAY_LABELS[normalizeLanguage(language)];

export const getLastGeminiErrorMessage = () => lastGeminiErrorMessage;

const getResponseErrorMessage = async (response: Response) => {
  try {
    const err = await response.json();
    return err?.error || err?.message || `Error del servidor (${response.status})`;
  } catch {
    return `Error del servidor (${response.status})`;
  }
};

const getGeminiFailureMessage = (error: unknown) => {
  const message = error instanceof Error ? error.message : String(error || "");
  const lower = message.toLowerCase();

  if (lower.includes("high demand") || lower.includes("unavailable") || lower.includes("503")) {
    return "Gemini está con alta demanda en este momento. Espera un poco y vuelve a intentarlo.";
  }

  if (lower.includes("timeout") || lower.includes("tard")) {
    return "Gemini tardó demasiado en responder. Revisa la conexión del servidor local e inténtalo otra vez.";
  }

  if (lower.includes("fetch failed") || lower.includes("network") || lower.includes("conectar")) {
    return "No se pudo conectar con Gemini. Revisa internet, firewall, VPN o el acceso a generativelanguage.googleapis.com.";
  }

  return message || "No se pudo generar con Gemini.";
};

const postGeminiRequest = async (url: string, body: unknown) => {
  const controller = new AbortController();
  const timeout = window.setTimeout(() => controller.abort(), GEMINI_CLIENT_TIMEOUT_MS);
  let localResponse: Response | null = null;
  let localError: unknown = null;

  try {
    localResponse = await authenticatedApiFetch(url, {
      method: "POST",
      body: JSON.stringify(body),
      signal: controller.signal
    });

    // En redes corporativas el proxy local puede no alcanzar Google aunque
    // Supabase siga disponible. En ese caso, usa la Edge Function autenticada.
    if (localResponse.ok || localResponse.status < 500) return localResponse;
  } catch (error) {
    localError = error instanceof DOMException && error.name === "AbortError"
      ? new Error(`Gemini timeout después de ${Math.round(GEMINI_CLIENT_TIMEOUT_MS / 1000)}s.`)
      : error;
  } finally {
    window.clearTimeout(timeout);
  }

  const edgeFunction = url.endsWith("/api/generate-workout")
    ? "generate-workout"
    : url.endsWith("/api/generate-diet")
      ? "generate-diet"
      : null;

  if (edgeFunction && isSupabaseEnabled() && supabase) {
    try {
      geminiLog(`Local Gemini unavailable; using Supabase Edge Function: ${edgeFunction}`);
      const { data, error } = await supabase.functions.invoke(edgeFunction, { body });
      if (error) throw error;

      const payload = typeof data === "string" ? JSON.parse(data) : data;
      if (!payload) throw new Error("La Edge Function no devolvió datos de Gemini.");
      return new Response(JSON.stringify(payload), {
        status: 200,
        headers: { "Content-Type": "application/json" }
      });
    } catch (edgeError) {
      geminiError("Gemini Edge Function fallback failed:", edgeError);
    }
  }

  if (localResponse) return localResponse;
  throw localError || new Error("No se pudo conectar con el servicio de Gemini.");
};

/**
 * Fallback local en caso de que la IA falle (403, cuota, etc)
 */
const getFallbackRoutine = (client: Client): Partial<Routine> => {
  const name = client.name || "Cliente";
  const goal = client.mainGoal || "Entrenamiento General";
  const level = client.experienceLevel || "Principiante";
  const days = client.trainingDays || ["Lunes", "Miércoles", "Viernes"];
  
  const exercisesConfig: Record<string, any[]> = {
    "Pérdida de peso": [
      { name: "Burpees", sets: "4", reps: "15", rest: "30s", notes: "Alta intensidad para quema calórica" },
      { name: "Sentadillas con salto", sets: "4", reps: "20", rest: "30s", notes: "Mantener ritmo constante" },
      { name: "Mountain Climbers", sets: "4", reps: "45s", rest: "30s", notes: "Core bien activado" }
    ],
    "Ganancia muscular": [
      { name: "Press de Banca", sets: "4", reps: "8-10", rest: "90s", notes: "Carga pesada con control" },
      { name: "Sentadilla con barra", sets: "4", reps: "8-10", rest: "120s", notes: "Profundidad máxima segura" },
      { name: "Dominadas", sets: "4", reps: "8-12", rest: "90s", notes: "Tracción escapular inicial" }
    ]
  };

  const selectedExercises = exercisesConfig[goal] || exercisesConfig["Ganancia muscular"];
  const finalExercises = days.flatMap(day => 
    selectedExercises.map(ex => ({ ...ex, day }))
  );

  return {
    name: `Plan Base: ${goal}`,
    description: `Generado con parámetros estándar. Por favor verifica tu conexión para obtener una versión optimizada por IA PRO.`,
    tags: ["básico", goal.toLowerCase()],
    exercises: finalExercises
  };
};

const getFallbackDiet = (client: Client): DietPlan => {
  const kcalMult = client.mainGoal?.includes("Pérdida") ? 0.8 : (client.mainGoal?.includes("Ganancia") ? 1.2 : 1.0);
  const weight = client.weight || 70;
  const kcal = (10 * weight + 1000) * 1.5 * kcalMult;

  return {
    title: `Plan Nutricional Base`,
    notes: `Generado con parámetros nutricionales estándar. Verifica tu conexión para obtener optimización por IA PRO.`,
    totalKcal: Math.round(kcal),
    totalProtein: Math.round(weight * 2),
    totalCarbs: Math.round(weight * 3),
    totalFats: Math.round(weight * 0.8),
    days: ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo"].map(d => ({
      day: d,
      meals: [
        { timeOfDay: "Desayuno", name: "Opción Base", description: "Proteína magra y carbohidrato complejo." },
        { timeOfDay: "Almuerzo", name: "Opción Base", description: "Proteína, vegetales y grasas saludables." },
        { timeOfDay: "Cena", name: "Opción Base", description: "Proteína ligera y fibra." }
      ]
    }))
  };
};

/**
 * Asegura que la rutina tenga el formato esperado por el frontend
 */
export const normalizeRoutine = (data: any, language: GeminiOutputLanguage = "es"): Partial<Routine> => {
  const copy = fallbackCopy[normalizeLanguage(language)];
  if (!data) return { name: copy.aiRoutineTitle, description: "", exercises: [], tags: [] };
  
  geminiLog("NORMALIZING ROUTINE START...");

  const ALL_DAYS = getDayLabels(normalizeLanguage(language));
  const dayKey = (value: any) => String(value || "")
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .trim();
  const rawDays = Array.isArray(data.days) ? data.days : [];
  const flatExercises = Array.isArray(data.exercises)
    ? [...data.exercises]
    : Array.isArray(data.workouts)
      ? [...data.workouts]
      : [];
  const flatExercisesByDay: Record<string, any[]> = Object.fromEntries(ALL_DAYS.map(day => [day, []]));

  flatExercises.forEach((exercise: any) => {
    const localizedExerciseDay = localizeDay(exercise?.day || exercise?.dayName, normalizeLanguage(language));
    const targetDay = ALL_DAYS.find(day => day === localizedExerciseDay);
    if (targetDay) flatExercisesByDay[targetDay].push({ ...exercise, day: targetDay });
  });

  const normalizedDays = ALL_DAYS.map(dayName => {
    const foundDay = rawDays.find((day: any) => localizeDay(day?.day || day?.name, normalizeLanguage(language)) === dayName || dayKey(day?.day || day?.name).includes(dayKey(dayName)));
    const structuredExercises = foundDay ? (foundDay.exercises || foundDay.workouts || []) : [];
    const dayExercises = Array.isArray(structuredExercises) && structuredExercises.length > 0
      ? structuredExercises
      : flatExercisesByDay[dayName];
    return {
      ...(foundDay || {}),
      day: dayName,
      exercises: Array.isArray(dayExercises) ? dayExercises : []
    };
  });

  let flattenedExercises = flatExercises;
  if (flattenedExercises.length === 0) {
    normalizedDays.forEach((day: any) => {
        day.exercises.forEach((ex: any) => {
            flattenedExercises.push({
                ...ex,
                day: day.day || "General"
            });
        });
    });
  }

  const normalized = {
    name: data.title || data.name || copy.aiRoutineTitle,
    description: data.summary || data.description || data.notes || copy.aiRoutineSummary,
    title: data.title || data.name || copy.aiRoutineTitle,
    summary: data.summary || data.description || copy.aiRoutineSummary,
    exercises: flattenedExercises,
    days: normalizedDays,
    tags: Array.isArray(data.tags) ? data.tags : ["ai"],
    warnings: Array.isArray(data.warnings) ? data.warnings : [],
    recommendations: Array.isArray(data.recommendations) ? data.recommendations : []
  };

  geminiLog("NORMALIZED ROUTINE EXERCISES COUNT:", normalized.exercises.length);
  return normalized;
};

/**
 * Asegura que el plan de dieta tenga el formato esperado
 */
export const normalizeDiet = (data: any, language: GeminiOutputLanguage = "es"): DietPlan => {
  const normalizedLanguage = normalizeLanguage(language);
  const copy = fallbackCopy[normalizedLanguage];
  if (!data) return { 
    title: copy.dietTitle, 
    totalKcal: 2000, totalProtein: 150, totalCarbs: 200, totalFats: 70, 
    days: [], meals: [], warnings: [], recommendations: [] 
  };

  geminiLog("NORMALIZING DIET START...");

  const rawDays = Array.isArray(data.days) ? data.days : [];
  const ALL_DAYS = getDayLabels(normalizedLanguage);
  
  const defaultMeals = normalizedLanguage === "en"
    ? [
        {
          timeOfDay: "Breakfast",
          name: "Egg-white omelet with spinach and oatmeal",
          description: "3 egg whites scrambled with fresh spinach, served with 50g of oatmeal cooked with cinnamon and water."
        },
        {
          timeOfDay: "Morning Snack",
          name: "Whey protein and fruit",
          description: "1 scoop of whey protein, or a handful of roasted peanuts, with 1 medium apple."
        },
        {
          timeOfDay: "Lunch",
          name: "Grilled chicken breast with brown rice and broccoli",
          description: "150g of chicken breast, 1 cup of brown rice or boiled sweet potato, and a generous serving of steamed broccoli."
        },
        {
          timeOfDay: "Afternoon Snack",
          name: "Greek yogurt with almonds",
          description: "150g of low-fat Greek yogurt mixed with 10 to 12 chopped almonds."
        },
        {
          timeOfDay: "Dinner",
          name: "Grilled fish with mixed green salad",
          description: "150g of seasonal white fish with lemon and a salad of cabbage, cucumber, and avocado."
        }
      ]
    : [
        {
          timeOfDay: "Desayuno",
          name: "Tortilla de claras de huevo con espinaca y avena",
          description: "3 claras de huevo revueltas con espinaca fresca, acompañado de 50g de avena cocida con canela y agua."
        },
        {
          timeOfDay: "Media Mañana",
          name: "Proteína de suero y fruta",
          description: "1 scoop de proteína de suero de leche, o un puñado de maní tostado, con 1 manzana mediana."
        },
        {
          timeOfDay: "Almuerzo",
          name: "Pechuga de pollo a la plancha con arroz integral y brócoli",
          description: "150g de pechuga de pollo, 1 taza de arroz integral o camote sancochado y una porción generosa de brócoli al vapor."
        },
        {
          timeOfDay: "Media Tarde",
          name: "Yogurt griego con almendras",
          description: "150g de yogurt griego bajo en grasa mezclado con 10 o 12 almendras picadas."
        },
        {
          timeOfDay: "Cena",
          name: "Pescado a la plancha con ensalada verde mixta",
          description: "150g de pescado blanco de estación con limón y ensalada de repollo, pepino y palta."
        }
      ];

  const normalizedDays = ALL_DAYS.map((dayName) => {
    // Check if the day is present in rawDays
    const foundDay = rawDays.find((d: any) => d?.day && localizeDay(d.day, normalizedLanguage) === dayName);

    let meals = foundDay && Array.isArray(foundDay.meals) ? [...foundDay.meals] : [];

    // Ensure all 5 key meal times exist: Desayuno, Media Mañana, Almuerzo, Media Tarde, Cena
    const mealTimes = MEAL_LABELS[normalizedLanguage];
    
    const finalMeals = mealTimes.map((timeName) => {
      const foundMeal = meals.find((m: any) => {
        if (!m || !m.timeOfDay) return false;
        const mt = String(m.timeOfDay).toLowerCase().trim();
        return mt === timeName.toLowerCase() || 
               (["Media Mañana", "Morning Snack"].includes(timeName) && (mt.includes("mañana") || mt.includes("morning") || mt.includes("colacion 1") || mt.includes("snack 1") || mt.includes("colación"))) ||
               (["Media Tarde", "Afternoon Snack"].includes(timeName) && (mt.includes("tarde") || mt.includes("afternoon") || mt.includes("colacion 2") || mt.includes("snack 2") || mt.includes("merienda") || mt.includes("colación")));
      });

      if (foundMeal) {
        return {
          timeOfDay: timeName,
          name: foundMeal.name || copy.mealName,
          description: foundMeal.description || copy.mealDescription
        };
      } else {
        const defaultMatch = defaultMeals.find(dm => dm.timeOfDay === timeName);
        return defaultMatch || {
          timeOfDay: timeName,
          name: copy.balancedMeal(timeName),
          description: copy.healthyMeal
        };
      }
    });

    return {
      day: dayName,
      meals: finalMeals
    };
  });

  const normalized = {
    title: data.title || copy.aiDietTitle,
    summary: data.summary || data.notes || copy.aiDietSummary,
    notes: data.notes || data.summary || copy.aiDietSummary,
    daily_calories: data.daily_calories || data.totalKcal || 2000,
    totalKcal: data.totalKcal || data.daily_calories || 2000,
    totalProtein: data.totalProtein || 150,
    totalCarbs: data.totalCarbs || 200,
    totalFats: data.totalFats || 70,
    days: normalizedDays,
    meals: Array.isArray(data.meals) ? data.meals : [],
    warnings: Array.isArray(data.warnings) ? data.warnings : [copy.hydration],
    recommendations: Array.isArray(data.recommendations) ? data.recommendations : [copy.adherence]
  };

  geminiLog("NORMALIZED DIET COMPLETED - 7 DAYS WITH 5 MEALS GUARANTEED");
  return normalized;
};

/**
 * Genera una rutina de entrenamiento usando nuestro backend (Gemini AI).
 */
export const generateWorkoutRoutine = async (
  client: Client,
  language: GeminiOutputLanguage = "es"
): Promise<Partial<Routine> | null> => {
  try {
    geminiLog("Calling Gemini workout");
    const response = await postGeminiRequest("/api/generate-workout", { clientData: client, language: normalizeLanguage(language) });

    if (!response.ok) {
      throw new Error(await getResponseErrorMessage(response));
    }
    
    const data = await response.json();
    lastGeminiErrorMessage = "";
    geminiLog("Gemini workout success");
    const normalized = normalizeRoutine(data, language);
    const hasExercises = normalized.exercises && normalized.exercises.length > 0;
    if (!hasExercises) {
      throw new Error("Gemini workout response incomplete: no exercises");
    }
    if (!Array.isArray(normalized.days) || normalized.days.length < 7) {
      throw new Error("Gemini workout response incomplete: weekly plan missing");
    }
    return {
      ...normalized,
      version: 1,
      source: "ai"
    };

  } catch (error) {
    lastGeminiErrorMessage = getGeminiFailureMessage(error);
    geminiError("Gemini failed, reason:", error);
    return null;
  }
};

/**
 * Genera un plan de dieta usando nuestro backend (Gemini AI).
 */
export const generateDietPlan = async (
  client: Client,
  language: GeminiOutputLanguage = "es"
): Promise<DietPlan | null> => {
  try {
    geminiLog("Calling Gemini diet");
    const response = await postGeminiRequest("/api/generate-diet", { clientData: client, language: normalizeLanguage(language) });

    if (!response.ok) {
      throw new Error(await getResponseErrorMessage(response));
    }

    const data = await response.json();
    lastGeminiErrorMessage = "";
    geminiLog("Gemini diet success");
    const hasSevenDays = Array.isArray(data.days) && data.days.length >= 7;
    if (!hasSevenDays) {
      throw new Error("Gemini diet response incomplete: 7 days required");
    }
    const normalized = normalizeDiet(data, language);
    return {
      ...normalized,
      version: 1,
      source: "ai"
    };

  } catch (error) {
    lastGeminiErrorMessage = getGeminiFailureMessage(error);
    geminiError("Gemini failed, reason:", error);
    return null;
  }
};
